#define BOOST_TEST_DYN_LINK

#include <boost/test/unit_test.hpp>

namespace SEPOLIA4::BOOST_UNIT_TEST_BLAS
{
	BOOST_AUTO_TEST_SUITE(BLAS_TESTS)

		BOOST_AUTO_TEST_CASE(TEST1)
		{
		}

	BOOST_AUTO_TEST_SUITE_END()
}
